### ISSUE TITLE
`pull` must return zipped content if `Accept` is set for it

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza#115]
Let's make `/pull` (from `front_push.rb`) to return zipped content, if `Accept` header is set for it.

**Comment by tank-bohr** [comment]
@yegor256 may I take this one?

**Comment by tank-bohr** [comment]
required by https://github.com/yegor256/judges/issues/84

**Comment by yegor256** [comment]
@tank-bohr new version deployed to Heroku, thanks!

**Comment by tank-bohr** [comment]
@yegor256 I believe this bug is closed by mistake

**Comment by yegor256** [comment]
@tank-bohr I re-opened it
