### ISSUE TITLE
add `job.ip` column

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza#129]
Let's catch the IP of a sender, when a new job is pushed through `front_push.rb`, and save this value to a new SQL column `job.ip`. Then, let's show this value in the `job.haml`.

**Comment by Suban05** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Suban05 go ahead, please

**Comment by yegor256** [comment]
@Suban05 I believe, it's fixed? When a task is fixed, don't forget to ask its author to close it.
