### ISSUE TITLE
inform about broken job only once

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza#134]
In the `pipeline.rb`, we notify the user via `human.notify()` when the job has errors. This notification is coming multiple times to Telegram, if jobs consequently have problems, one after another. It would be better, if we notify the user once and then skip notifications on all erroneous jobs after than. Simply put, before notifying the user let's check the status of the previous job with the same name. If there were errors, skip the notification.

**Comment by Suban05** [comment]
@yegor256 May I take this one?

**Comment by yegor256** [comment]
@Suban05 this is also fixed already: https://github.com/zerocracy/baza/blob/master/objects/baza/pipeline.rb#L131-L143
