### ISSUE TITLE
`front_push.rb` must accept gzipped content not only on `POST` request but on the `PUT` request as well

### ISSUE THREAD

**Issue by tank-bohr** [zerocracy/baza#135]
required for https://github.com/yegor256/judges/issues/83

related to #101

**Comment by tank-bohr** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@tank-bohr please, go ahead

**Comment by 0crat** [comment]
@tank-bohr Thanks for reporting a new bug! You've earned +15 points. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that [doesn't look](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) as good as you might expect, [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) it. Your running balance is +15.
