### ISSUE TITLE
Error 500 occurs in case of an incorrect SQL query in the SQL console

### ISSUE THREAD

**Issue by Suban05** [zerocracy/baza#136]
When we try to execute an incorrect SQL query in the SQL console (/sql) we see error 500.
Let's handle the error and display it on the page

**Comment by yegor256** [comment]
@Suban05 good idea, thanks

**Comment by yegor256** [comment]
@Suban05 next time, [ping me](https://www.yegor256.com/2024/04/01/ping-me-please.html) when you report a bug

**Comment by Suban05** [comment]
@yegor256 okay, thanks

**Comment by 0crat** [comment]
@Suban05 Thanks for reporting a new bug! You've earned +15 points. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that [doesn't look](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) as good as you might expect, [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) it. Your running balance is +40.

**Comment by Suban05** [comment]
@yegor256 now I try to execute an incorrect SQL query, and I see a page with a full error message. Earlier, I saw just an error 500.
![image](https://github.com/user-attachments/assets/fd5872fa-7635-4e5e-a8d4-39b55f0b239c)
maybe we can close this ticket?

**Comment by yegor256** [comment]
@Suban05 indeed, let's close it
