### ISSUE TITLE
the page about a single vale is missing at `/valves/[0-9]+`

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza#139]
Let's add a page in `front_valves.rb` that will show all the details about a single valve, similar to how we show the information about a single job in `front_jobs.rb`. Let's also mention this page in `valves.enter()` when we notify a human via `human.notify()`. Now we mention just `https://www.zerocracy.com/valves`.

**Comment by Suban05** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Suban05 sure, go ahead please
