### ISSUE TITLE
let's notify the user when a new token is added

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza#141]
Let's do `human.notify()` from `tokens.add()`, in order to inform the user that a new token has been just added to his account.

**Comment by Suban05** [comment]
@yegor256 I have some questions
Do we need to notify about error messages?
Do we need testing for this feature? I have checked the use of `human.notify` in other files, but there are no tests for it. Only tests for `tbot`.

**Comment by yegor256** [comment]
@Suban05 what error message you have in mind? I didn't get this question. As for the tests -- indeed we should write them.

**Comment by Suban05** [comment]
@yegor256 I mean this, for example:
https://github.com/zerocracy/baza/blob/161becd3ba3e54e13d98539a5afc636fea4a2ad5/objects/baza/tokens.rb#L47

**Comment by yegor256** [comment]
@Suban05 exceptions are a different story. In this ticket we only care about Tbot notifications.
