### ISSUE TITLE
let's notify the user when a new secret is added

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza#142]
Let's do `human.notify()` from `secrets.add()`, in order to inform the user that a new secret has been just added to his account.

**Comment by abhedanil** [comment]
Hi , could you describe the issue , so i can take this up and start working !

**Comment by yegor256** [comment]
@abhedanil see how we notify `human` in, for example, `account.rb` method `top_up`. Here, we need something similar.

**Comment by abhedanil** [comment]
Ok. Please assign it to me

**Comment by yegor256** [comment]
@abhedanil only the best technologies!

**Comment by abhedanil** [comment]
I can take it up. Please assign it to me

**Comment by yegor256** [comment]
@abhedanil go ahead, it's yours!
