### ISSUE TITLE
Enforce MultilineAssignmentLayout cop

### ISSUE THREAD

**Issue by tank-bohr** [zerocracy/baza#144]
> @tank-bohr it's better to format like this:

```
source =
  if ...
    ...
  else
    ...
  end
```

_Originally posted by @yegor256 in https://github.com/zerocracy/baza/issues/143#issuecomment-2254363333_

**Comment by tank-bohr** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@tank-bohr sure, go ahead

**Comment by tank-bohr** [comment]
@yegor256, why is it not a bug?

**Comment by yegor256** [comment]
@tank-bohr my bad, fixed

**Comment by 0crat** [comment]
@tank-bohr Thanks for reporting a new bug! You've earned +15 points. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that [doesn't look](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) as good as you might expect, [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) it. Your running balance is [+64](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).
