### ISSUE TITLE
`lock.ip` column is missing

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza#156]
Let's add `ip` column to the `lock` table and then record the IP of the requestor of every lock. Let's show the IP in the `locks.haml` view.

**Comment by yegor256** [comment]
@Suban05 go ahead, please

**Comment by Suban05** [comment]
@yegor256 after merging the pr https://github.com/zerocracy/baza/pull/204, the pull request https://github.com/zerocracy/baza/pull/214 for this issue was removed.

**Comment by yegor256** [comment]
@Suban05 I merged #214

**Comment by Suban05** [comment]
@yegor256 yes, but I don't see changes in the `master` branch:
https://github.com/zerocracy/baza/blob/9bf358bdf950e2ea040046298ab9761b7a2e7afa/objects/baza/locks.rb#L80

That's how it should be:
https://github.com/Suban05/baza/blob/4456397d8f9d739403e5a9150405c37585d0b06c/objects/baza/locks.rb#L81

**Comment by yegor256** [comment]
@Suban05 oops, most probably it's a mistake on my side. Can you please submit the PR again? I will merge it again.
