### ISSUE TITLE
incorrect call of `locks.lock()` in `front_push`

### ISSUE THREAD

**Issue by Suban05** [zerocracy/baza#168]
The parameter `name` is missing.

https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L145
https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L155
https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L165
https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L172
https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L186

**Comment by Suban05** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Suban05 go ahead!

**Comment by 0crat** [comment]
@Suban05 "Great job reporting that new bug! 🐛 As per our policy, you've earned **+15 points** for this valuable contribution. Your keen eye helps enhance our project's quality. Remember, if you spot anything else that [doesn't look](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) up to par, [don't hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) it – each accepted bug report earns you points! Your current balance stands at [+213](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the excellent work!"
