### ISSUE TITLE
`bundle update` doesn't work in the `rake` workflow

### ISSUE THREAD

**Issue by Suban05** [zerocracy/baza#170]
for example: https://github.com/zerocracy/baza/actions/runs/10264809221/job/28399644704

**Comment by Suban05** [comment]
@yegor256 added a new ticket

**Comment by yegor256** [comment]
@Suban05 thanks, indeed a bug... I don't know what's going on, though

**Comment by yegor256** [comment]
@Suban05 some magic here. I fixed it by upgrading to Ruby 3.3 and Ubuntu 24.

**Comment by Suban05** [comment]
@yegor256 thanks!
