### ISSUE TITLE
`bundle exec rake` is red

### ISSUE THREAD

**Issue by Suban05** [zerocracy/baza#173]
After this change https://github.com/zerocracy/baza/commit/02bea3a52358de71f631ddbc7938707983769242 rubocop failed

**Comment by 0crat** [comment]
@Suban05 Thanks for submitting this ticket! However, as you see, it was not accepted by the team, which is sad. You've earned -20 points. By reporting bugs or suggesting enhacements, you help our project improve its quality. Please, don't be discouraged. Instead, try to be more careful next time, and [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) bugs. Your running balance is [+302](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Comment by Suban05** [comment]
@yegor256 but this issue was accepted, because pr was merged. why -20 points?

**Comment by yegor256** [comment]
@Suban05 issue is "accepted" when "bug" or "enhancement" label is attached. Here, it was closed but not label attached.

**Comment by Suban05** [comment]
@yegor256 This issue was a bug, but it was fixed quickly and closed automatically, without a label being attached. I think we should not deduct 20 points for this. What do you think about it?

**Comment by yegor256** [comment]
@Suban05 in general this means that the issue was not accepted by the architect of the project (which is a violation of discipline). It's good that the pull request merged, but that's a different story (and different points awarded to the programmer).

**Comment by yegor256** [comment]
@Suban05 I'm thinking, maybe we need some place where each rule of our policy is published and people can discuss them...
