### ISSUE TITLE
ipgeolocation requests are not cached

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza#239]
Currently, we make requests to their server on every IP address. I believe, most IP addresses will be repeated (since they are all from Github.com). Let's cache them, using `settings.zache`, similar to how we cache other data.

Moreover, I would change the implementation we have now. Instead of making the HTTP request to ipgeolocation server while generating our HTML, we should render the `<img src="https://www.zerocracy.com/flag-of/8.8.8.8" class="flag">`. Then, we should define a new Sinatra entry point `/flag-of/.*` where we make a request to ipgeolocation server, download the flag from their server, and return its binary content.

**Comment by yegor256** [comment]
@Suban05 can you fix this?

**Comment by Suban05** [comment]
@yegor256 yes, of course
