### ISSUE TITLE
reject uploads if their size is over a certain limit

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza#44]
In `front_push.rb` we accept any possible size of an upload. Let's introduce an upper limit and reject too large uploads.

**Comment by Suban05** [comment]
Hello. 
I added a limit of 10 MB, but I'm not sure.
What limit do we need?

**Comment by yegor256** [comment]
@Suban05 10Mb should be enough for now

**Comment by yegor256** [comment]
@Suban05 thanks!
